paths:
  path_to_prompts: app/participant/prompts

query_validator:
  class_name: LLMQueryValidator
  model_id: "anthropic.claude-3-haiku-20240307-v1:0"

hard_extractor:
  class_name: LLMHardFactExtractor
  model_id: "anthropic.claude-3-haiku-20240307-v1:0"

soft_extractor:
  class_name: DumbSoftExtractor
  anchor_path: configs/soft_extractor_anchors.yaml
  importance_keywords_path: configs/soft_extractor_importance_keywords.yaml

soft_filter:
  class_name: HybridSimilarityFilter
  top_k: 10

ranker:
  class_name: DumbRanker