paths:
  path_to_prompts: app/participant/prompts

query_validator:
  class_name: LLMQueryValidator
  model_id: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
  # model_id: "amazon.nova-micro-v1:0"
  # model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"

hard_extractor:
  class_name: LLMHardFactExtractor
  # model_id: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
  # model_id: "amazon.nova-micro-v1:0"
  model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"

soft_extractor:
  class_name: LLMSoftExtractor
  # model_id: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
  # model_id: "amazon.nova-micro-v1:0"
  model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"
  anchor_path: configs/soft_extractor_anchors.yaml
  importance_keywords_path: configs/soft_extractor_importance_keywords.yaml

hard_filter:
  target_candidates: 200

soft_filter:
  class_name: AugmentorFilter
  target_candidates: 50
  enable_dense_vector: true
  enable_sparse_weights: true
  enable_image_vector: true
  enable_boost_fields: true
  enable_query_text_en: true
  enable_anchor_features: true
  anchor_threshold: 0.5
  sparse_k_for_scoring: 30  # how many top BM25 features for scoring

reranker:
  # class_name: CohereReRanker
  # model_id: "cohere.rerank-v3-5:0"
  class_name: LLMReRanker
  # model_id: "us.anthropic.claude-sonnet-4-6"
  # model_id: "us.anthropic.claude-haiku-4-5-20251001-v1:0"
  # model_id: "amazon.nova-micro-v1:0"
  model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"
  target_candidates: 10
  region: "us-east-1"