hard_extractor:
  class_name: DumbHardExtractor

soft_extractor:
  class_name: LLMSoftExtractor
  anchor_path: configs/soft_extractor_anchors.yaml
  importance_keywords_path: configs/soft_extractor_importance_keywords.yaml

soft_filter:
  class_name: HybridSimilarityFilter
  top_k: 10

ranker:
  class_name: DumbRanker

api_key_openrouteservice: "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjExZTNhODRlZmE1MjQ4ZmM5YzgzMmJkOTMzN2IxYzEwIiwiaCI6Im11cm11cjY0In0="
profile: "driving-car" # {driving-car, cycling-regular, foot-walking}