1.0:
  - must
  - essential
  - needs
  - required
  - mandatory
  - unbedingt
  - muss
  - notwendig
  - zwingend
0.7:
  - prefer
  - looking for
  - searching
  - like to have
  - bevorzugt
  - wäre toll
  - suche
  - hät gärn
0.4:
  - ideally
  - maybe
  - possible
  - nice to have
  - wenn möglich
  - vielleicht
  - wär schön
